### ISSUE TITLE
 Краш на Android 5 и 6

### ISSUE THREAD

**Issue by Qutbiddin** [JivoChat/JivoSDK-Android#53]
после обновление версии 1.2.0 на андроид ниже 7 апп крашится
...
Fatal Exception: java.lang.NoClassDefFoundError:
       at javax.net.ssl.SNIServerName.<clinit>(SNIServerName.java)
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:309)
       at java.lang.Class.forName(Class.java:273)
       at com.neovisionaries.ws.client.Misc.getConstructor(Misc.java:398)
       at com.neovisionaries.ws.client.SNIHelper.initialize(SNIHelper.java:51)
       at com.neovisionaries.ws.client.SNIHelper.<clinit>(SNIHelper.java:38)
       at com.neovisionaries.ws.client.SocketInitiator$SocketRacer.run(SocketInitiator.java:123)
...

OkHttp sdk.jivosite.com:
       at com.android.org.conscrypt.NativeCrypto.SSL_read(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:699)
       at okio.InputStreamSource.read(JvmOkio.kt:94)
       at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
       at okio.internal._RealBufferedSourceKt.commonRequest(_RealBufferedSourceKt.java:60)
       at okio.RealBufferedSource.request(RealBufferedSource.kt:68)
       at okio.RealBufferedSource.require(RealBufferedSource.kt:1)
       at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:89)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:618)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.<init>(Http2Connection.kt:609)
       at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
       at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
       at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:1)
       at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
...

**Comment by tavtorkin-jivo** [comment]
@Qutbiddin Здравствуйте!
Можете [включить](https://github.com/JivoChat/JivoSDK-Android/blob/develop/README_ru.md#%D0%B2%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BB%D0%BE%D0%B3%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F) логи SDK ?
Требуется больше информация,  какая версия OS, устройство?
На каком этапе происходит падение?
